### ISSUE TITLE
can't require 'ripple'

### ISSUE THREAD

**Issue by xiaok** [kevinejohn/ripple-lib-rpc-ruby#4]
```
2.2.7 :001 > require 'ripple'
LoadError: cannot load such file -- ripple
	from /Users/gaoyixin/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/gaoyixin/.rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from (irb):1
	from /Users/gaoyixin/.rvm/rubies/ruby-2.2.7/bin/irb:11:in `<main>'
```

```
ruby -v
ruby 2.2.7p470 (2017-03-28 revision 58194) [x86_64-darwin16]
```

**Comment by kevinejohn** [comment]
This library is at least a few years out-of-date

**Comment by krtschmr** [comment]
@kevinejohn  at least?! lmao
